# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/vis/disable
/tracking/verbose 0

# Select detector
/det/select uoft1

# Initialize
/run/initialize
/run/printProgress 100


## Step limiter
/control/execute ../macros/init_limit.mac


## Setup CRY generator
/gen/select cry
/gen/cry/pathname ../studies/uoft/cosmic/cry_all_cms_0m.conf
# Filter events that contains proton (2212) and is above 2.67 GeV
# /gen/cry/particle_pdgid 2212 
# /gen/cry/abstime 1
/gen/cry/ekin_low 0 GeV
/gen/cry/ekin_high 100 TeV

/gen/cry/shape 1
/gen/cry/box 2. 2. 2. m
/gen/cry/offset 0. 0. 2. m

/run/beamOn {events}
#/run/dumpCouples