# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
# /run/numberOfThreads 4
#
## Initialize kernel
/vis/disable
/tracking/verbose 0

## Select detector, one of {uoft1, mu40v0}
/det/select mu40v0

## Extend the max energy to 1 PeV 
/process/eLoss/maxKinEnergy 1 PeV
/process/had/maxEnergy 1 PeV

## Initialize run
/run/initialize
/run/printProgress 1



# Special run setting - production cut for charged particle range, global setting.
# Secondaries with range less than this nunmber will not be generated.
# Primary particle just goes through continuous energy loss
# Step limiter
/control/execute ../macros/init_limit.mac

## Specify the ROOT file to recreate
/gen/recreate/pathname ../tests/cosmic_generator/neutron_100TeV.root
## Setup recreate generator
/gen/select recreate

/run/beamOn 10


## !! NO NEED TO CALL  run beamOn !!
## ALL EVENTS WITHIN THE ROOT FILE WILL AUTOMATICALLY BE GENERATED