# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
# /run/numberOfThreads 4
#
## Initialize kernel
/vis/disable
/tracking/verbose 0

## Select detector, one of {uoft1, mu40v0}
/det/select mu40v0

## Initialize run
/run/initialize
/run/printProgress 1000
# /run/numberOfThreads 1


## Special run setting 

## Step limiter
/control/execute ../macros/init_limit.mac

## Setup PARMA generator
/gen/select parma
/gen/parma/pathname ../tests/mathusla40/parma_config_mathusla40.conf
# pdgids
# 13: muon
# 11: electron
# 2212: proton
# 2112: neutron
/gen/parma/particle_pdgid 2212
/gen/parma/ekin_low 0 GeV
/gen/parma/ekin_high 200 GeV
/gen/parma/shape 1
/gen/parma/box 55. 50. 20. m
/gen/parma/offset 2.5 0. 20. m


## Update the PARMA generator settings
/gen/parma/update


/run/beamOn 10000
#/run/dumpCouples