# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/vis/disable
/tracking/verbose 0

# Select detector
/det/select mu40v0

# Initialize
/run/initialize
/run/printProgress 100


## Step limiter
/control/execute ../macros/init_limit.mac


## Setup CRY generator
/gen/select cry
#/gen/cry/pathname ../macros/generators/cry_all.conf
# /gen/cry/pathname ../macros/generators/cry_proton.conf
/gen/cry/pathname ../macros/generators/cry_neutron.conf
# Filter events that contains proton (2212) and is above 2.67 GeV
# /gen/cry/particle_pdgid 2212
/gen/cry/ekin_low 0 GeV
# /gen/cry/ekin_high 200 GeV

/gen/cry/shape 1
/gen/cry/box 55. 50. 20. m
/gen/cry/offset_x 2.5 m

/run/beamOn 100000
#/run/dumpCouples