# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4


# Select detector
/det/select mu40v0

# Initialize kernel
/run/initialize
/vis/disable
#
# Default kinematics: 
# electron 50 MeV in direction (0.,0.,1.)
# 1 event with tracking/verbose
#
/tracking/verbose 0
/run/printProgress 5


# muon 300 MeV in direction (0.,0.,1.)
# 3 events
#
/gun/particle mu-
/gun/energy 1 GeV
/gun/position 25 3 10 m
/gun/direction -2 0 -1 m


/gun/particle mu-
/gun/position 5 5 20 m
/gun/energy 1 GeV
/gun/direction 0 0 -1 m

/gun/particle mu-
/gun/position 25 5 5 m
/gun/energy 1 GeV
/gun/direction -1 0 0 m

/run/beamOn 10

