# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/vis/disable
/tracking/verbose 0
/run/initialize
/run/printProgress 100
# /run/numberOfThreads 1


# Special run setting 

# Production cut for charged particle range, global setting.
# Secondaries with range less than this nunmber will not be generated.
# Primary particle just goes through continuous energy loss
/run/setCut 10 mm

## Neutron killer
# Disable neutron killer:
# /process/inactivate nKiller
/physics_engine/neutron/timeLimit 500 ns
/physics_engine/neutron/energyLimit 1.0 MeV


## Setup PARMA generator
/gen/select parma
/gen/parma/pathname ../macros/generators/parma_default.conf
/gen/parma/particle_pdgid 2112
/gen/parma/ekin_low 1 GeV
/gen/parma/ekin_high 200 GeV
/gen/parma/shape 1
/gen/parma/box 2. 2. 2. m
# Update the PARMA generator settings
/gen/parma/update


/tracking/verbose 0
/run/beamOn 1970
#/run/dumpCouples