# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
/vis/disable
#
# Default kinematics: 
# electron 50 MeV in direction (0.,0.,1.)
# 1 event with tracking/verbose
#
/tracking/verbose 1
/tracking/verbose 0
/run/printProgress 5


# muon 300 MeV in direction (0.,0.,1.)
# 3 events
#
/gun/particle neutron
/gun/energy 4000 MeV
/run/beamOn 2000

