# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/vis/disable
/run/initialize
/run/printProgress 100

## Setup CRY generator
/gen/select cry
/gen/cry/pathname ../macros/generators/cry_proton.file
/gen/cry/ekin_low 2.67 GeV

/tracking/verbose 0
/run/beamOn 1000