# Macro file for example Mu
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/vis/disable
/tracking/verbose 0

# Select detector
/det/select mu40v0

# Initialize
/run/initialize
/run/printProgress 1000


## Step limiter
/control/execute ../macros/init_limit.mac


## Setup CRY generator
/gen/select cry
/gen/cry/pathname ../studies/mathusla40/cosmic_mu/scripts/cry_muon_cms_0m.conf
/gen/cry/particle_pdgid 13
/gen/cry/ekin_low 0 GeV
/gen/cry/ekin_high 100 TeV

/gen/cry/shape 1
#/gen/cry/box 55. 50. 20. m
#/gen/cry/offset 2.5 0. 20. m
/gen/cry/box 45. 40. 18. m
/gen/cry/offset 2.5 0. 18. m

/run/beamOn {events}
#/run/dumpCouples